name: Android CI

on:
  push:
    branches: [ 'master', 'dev' ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: [ 'master', 'dev' ]

permissions:
  contents: read
  packages: write
  actions: write
  checks: write

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  test-and-build:
    name: Test and Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          cache-version: 1
          
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle config path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate bubble-phone-keystore.jks
        run: |
          mkdir -p "$GITHUB_WORKSPACE/keystore"
          echo '${{ secrets.BUBBLE_PHONE_KEYSTORE }}' | base64 --decode > "$GITHUB_WORKSPACE/keystore/bubble-phone-keystore.jks"
          
      - name: Run Fastlane CI
        run: bundle exec fastlane ci
        env:
          CI: true
          FASTLANE_SKIP_UPDATE_CHECK: true
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          KEYSTORE_PASSWORD: ${{ env.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ env.KEY_ALIAS }}
          KEY_PASSWORD: ${{ env.KEY_PASSWORD }}
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: |
            **/build/test-results/**/*
            **/build/reports/tests/**/*
          retention-days: 7
          
      - name: Upload APK
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
          retention-days: 7
          compression-level: 9
  
  bump-version:
    name: Bump Version
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    # Dar permisos explícitos para escribir en el repositorio
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          cache-version: 1
          
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle config path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version and push changes
        run: bundle exec fastlane bump_version
        env:
          CI: true
          FASTLANE_SKIP_UPDATE_CHECK: true
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  deploy-internal:
    name: Deploy to Internal Testing
    needs: bump-version
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          cache-version: 1
          
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle config path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate play-store-credentials.json
        run: |
          echo '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}' > "$GITHUB_WORKSPACE/play-store-credentials.json"
      
      - name: Generate bubble-phone-keystore.jks
        run: |
          mkdir -p "$GITHUB_WORKSPACE/keystore"
          echo '${{ secrets.BUBBLE_PHONE_KEYSTORE }}' | base64 --decode > "$GITHUB_WORKSPACE/keystore/bubble-phone-keystore.jks"
        
      - name: Deploy to Internal Testing
        run: bundle exec fastlane internal
        env:
          CI: true
          FASTLANE_SKIP_UPDATE_CHECK: true
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          ENVIRONMENT: ${{ github.ref == 'refs/heads/master' && 'production' || 'development' }}
          KEYSTORE_PASSWORD: ${{ env.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ env.KEY_ALIAS }}
          KEY_PASSWORD: ${{ env.KEY_PASSWORD }}
    
          # TRACK: internal
