name: Android CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test-and-build:
    name: Test and Build Android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: |
        cd $GITHUB_WORKSPACE
        bundle install

    - name: Run Fastlane CI
      run: bundle exec fastlane ci
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
