name: iOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Permisos necesarios para el token de GitHub
permissions:
  contents: read
  packages: write

jobs:
  test-and-build:
    name: Test and Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      # Configurar Ruby y Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'  # Ajusta según sea necesario
          bundler-cache: true
          
      - name: Install Bundler
        run: gem install bundler
        
      - name: Install Fastlane
        run: |
          cd iosApp
          bundle install --path vendor/bundle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run Fastlane CI
        run: |
          cd iosApp
          bundle exec fastlane ci
        env:
          CI: true
          
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-frameworks
          path: |
            composeApp/build/bin/iosX64/debugFramework/
            composeApp/build/bin/iosSimulatorArm64/debugFramework/
            composeApp/build/bin/iosX64/releaseFramework/
            composeApp/build/bin/iosSimulatorArm64/releaseFramework/
          retention-days: 5
