name: iOS CI

on:
  push:
    branches: [ 'master', 'dev' ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: [ 'master', 'dev' ]

permissions:
  contents: read
  packages: write
  actions: write
  checks: write

jobs:
  test-and-build:
    name: Test and Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          cache-version: 1
          
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version
          
      - name: Install Fastlane
        working-directory: ./iosApp
        run: |
          gem install bundler
          bundle config path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Generate env.properties
        run: |
          echo '${{ secrets.ENV_PROPERTIES }}' > env.properties

      - name: Run Fastlane CI
        working-directory: ./iosApp
        run: bundle exec fastlane ci
        env:
          CI: true
          FASTLANE_SKIP_UPDATE_CHECK: true
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: |
            iosApp/fastlane/test_output/**/*
            iosApp/fastlane/report.xml
          retention-days: 7
          
      - name: Upload frameworks
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-frameworks
          path: |
            composeApp/build/bin/iosX64/debugFramework/**
            composeApp/build/bin/iosSimulatorArm64/debugFramework/**
            composeApp/build/bin/iosX64/releaseFramework/**
            composeApp/build/bin/iosSimulatorArm64/releaseFramework/**
          retention-days: 7
          compression-level: 9
