name: iOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-build:
    name: Test and Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run iOS Tests
        run: |
          # Run tests for iOS simulator (x86_64)
          ./gradlew :composeApp:iosX64Test
          
          # Run tests for iOS device (arm64)
          ./gradlew :composeApp:iosSimulatorArm64Test
        
      - name: Build Debug Framework
        run: |
          # Build debug framework for iOS simulator (x86_64)
          ./gradlew :composeApp:linkDebugFrameworkIosX64
          
          # Build debug framework for iOS simulator (arm64)
          ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64
          
      - name: Build Release Framework
        run: |
          # Build release framework for iOS simulator (x86_64)
          ./gradlew :composeApp:linkReleaseFrameworkIosX64
          
          # Build release framework for iOS simulator (arm64)
          ./gradlew :composeApp:linkReleaseFrameworkIosSimulatorArm64
